Develop
GermanKulchinksii/mesto pull request #1
Opened 2022-05-13 18:29 UTC by GermanKulchinksii

ne bei plz

2022-05-13 18:30 UTC, Kuzuru requested changes
Отсутствует github-pages

2022-05-13 21:43 UTC, Kuzuru requested changes
1. При открытии popup-формы фон не затемняется
2. Кнопка внутри формы не выполнена по макету
3. Форма выполнена не по макету
4. Используется шрифт не из макета
5. Крестик находится не в правильной позиции, как указано в макете
6. Кнопка "Сохранить" не работает
7. Карточки свёрстаны не по макету
8. Копирайт внизу страницы должен быть выполнен текстом, а не `<img>`
9. При наведении на лайк нет `cursor: pointer`
10. Картинки не сжаты, сайт грузится довольно медленно для такой комплектации
11. Отсутствуют `placeholder` у `input` внутри popup-формы
12. Логотип на начальном экране выглядит размыто
13. Поля "Жак-Ив Кусто" и "Исследователь океана" не выровнены

2022-05-21 11:01 UTC, Kuzuru commented
Что за кукож?
![image](https://user-images.githubusercontent.com/49472529/169648723-6a17cc24-5dbc-4d17-965c-ae2c0d4c39a4.png)

2022-05-21 11:02 UTC, Kuzuru commented
Шрифты и отступы не по макету
![image](https://user-images.githubusercontent.com/49472529/169648744-374a9343-e092-4155-ad14-0f2768cb0783.png)

2022-05-21 11:03 UTC, Kuzuru commented
1. Отсутствует затемнённый фон, когда открыт попап
2. Шрифты не по макету
3. `<input>`(-ы) не по макету

![image](https://user-images.githubusercontent.com/49472529/169648765-53774424-1198-4922-a8f9-a35947115972.png)

2022-05-21 11:05 UTC, Kuzuru commented
При нажатии на "Enter" или "Сохранить" скрипт не изменяет на странице информацию о пользователе

2022-05-21 11:06 UTC, Kuzuru commented
Есть ошибки в консоли

![image](https://user-images.githubusercontent.com/49472529/169648880-6054c195-3417-40f2-af5d-73d634578e88.png)

2022-05-21 11:12 UTC, Kuzuru requested changes
Жду исправлений

2022-05-31 18:11 UTC, GermanKulchinksii commented
Ожидаю проверки

2022-06-01 17:43 UTC, Kuzuru commented
Ширина начального экрана больше, чем указано в макете
![image](https://user-images.githubusercontent.com/49472529/171468840-74706a6e-6c04-4b62-9913-c93f1709054f.png)

2022-06-01 17:44 UTC, Kuzuru commented
1. SVG Лайка не на своём месте
2. Размер шрифта карточек не по макету

![image](https://user-images.githubusercontent.com/49472529/171468958-f8904a08-f803-42be-a312-ab8b0501e027.png)

2022-06-01 17:48 UTC, Kuzuru commented
Я даже не буду это комментировать... Исправить.

![image](https://user-images.githubusercontent.com/49472529/171469758-ed142914-9d5a-4673-8068-c5f1dcc0b7c6.png)

2022-06-01 17:48 UTC, Kuzuru commented
Popup-форма не по размерам макета. Исправить
![image](https://user-images.githubusercontent.com/49472529/171469892-e81e5795-e483-4c44-907b-f4f47c75b79d.png)

2022-06-01 17:51 UTC, Kuzuru requested changes
Ожидаю изменений

2022-06-11 19:07 UTC, GermanKulchinksii commented
ожидаю проверки

2022-06-14 12:53 UTC, Kuzuru commented
После открытия попапа пропадает скролл, из-за чего страница уезжает. Скролл можно на всей странице в принципе выключить (скрыть), при этом оставляя возможность скроллить

![image](https://user-images.githubusercontent.com/49472529/173581670-bf2f8a61-588b-4717-ba76-3d449c58905f.png)
![image](https://user-images.githubusercontent.com/49472529/173581697-a7f71aed-2f7b-4192-a785-e4f17af56e14.png)

2022-06-14 12:55 UTC, Kuzuru approved these changes

2022-06-14 13:05 UTC, merged